// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protocol/nylon_ipc.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReloadResult int32

const (
	ReloadResult_NOOP             ReloadResult = 0
	ReloadResult_APPLIED          ReloadResult = 1
	ReloadResult_REJECTED         ReloadResult = 2
	ReloadResult_RESTART_REQUIRED ReloadResult = 3
)

// Enum value maps for ReloadResult.
var (
	ReloadResult_name = map[int32]string{
		0: "NOOP",
		1: "APPLIED",
		2: "REJECTED",
		3: "RESTART_REQUIRED",
	}
	ReloadResult_value = map[string]int32{
		"NOOP":             0,
		"APPLIED":          1,
		"REJECTED":         2,
		"RESTART_REQUIRED": 3,
	}
)

func (x ReloadResult) Enum() *ReloadResult {
	p := new(ReloadResult)
	*p = x
	return p
}

func (x ReloadResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReloadResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_nylon_ipc_proto_enumTypes[0].Descriptor()
}

func (ReloadResult) Type() protoreflect.EnumType {
	return &file_protocol_nylon_ipc_proto_enumTypes[0]
}

func (x ReloadResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReloadResult.Descriptor instead.
func (ReloadResult) EnumDescriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{0}
}

type EndpointTransport int32

const (
	EndpointTransport_UDP      EndpointTransport = 0
	EndpointTransport_FAKE_TCP EndpointTransport = 1
)

// Enum value maps for EndpointTransport.
var (
	EndpointTransport_name = map[int32]string{
		0: "UDP",
		1: "FAKE_TCP",
	}
	EndpointTransport_value = map[string]int32{
		"UDP":      0,
		"FAKE_TCP": 1,
	}
)

func (x EndpointTransport) Enum() *EndpointTransport {
	p := new(EndpointTransport)
	*p = x
	return p
}

func (x EndpointTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_nylon_ipc_proto_enumTypes[1].Descriptor()
}

func (EndpointTransport) Type() protoreflect.EnumType {
	return &file_protocol_nylon_ipc_proto_enumTypes[1]
}

func (x EndpointTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointTransport.Descriptor instead.
func (EndpointTransport) EnumDescriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{1}
}

type EndpointProbeStatus int32

const (
	EndpointProbeStatus_ENDPOINT_PROBE_STATUS_UNSPECIFIED EndpointProbeStatus = 0
	EndpointProbeStatus_ENDPOINT_PROBE_REPLIED            EndpointProbeStatus = 1
	EndpointProbeStatus_ENDPOINT_PROBE_TIMEOUT            EndpointProbeStatus = 2
	EndpointProbeStatus_ENDPOINT_PROBE_SEND_ERROR         EndpointProbeStatus = 3
	EndpointProbeStatus_ENDPOINT_PROBE_RESOLVE_ERROR      EndpointProbeStatus = 4
)

// Enum value maps for EndpointProbeStatus.
var (
	EndpointProbeStatus_name = map[int32]string{
		0: "ENDPOINT_PROBE_STATUS_UNSPECIFIED",
		1: "ENDPOINT_PROBE_REPLIED",
		2: "ENDPOINT_PROBE_TIMEOUT",
		3: "ENDPOINT_PROBE_SEND_ERROR",
		4: "ENDPOINT_PROBE_RESOLVE_ERROR",
	}
	EndpointProbeStatus_value = map[string]int32{
		"ENDPOINT_PROBE_STATUS_UNSPECIFIED": 0,
		"ENDPOINT_PROBE_REPLIED":            1,
		"ENDPOINT_PROBE_TIMEOUT":            2,
		"ENDPOINT_PROBE_SEND_ERROR":         3,
		"ENDPOINT_PROBE_RESOLVE_ERROR":      4,
	}
)

func (x EndpointProbeStatus) Enum() *EndpointProbeStatus {
	p := new(EndpointProbeStatus)
	*p = x
	return p
}

func (x EndpointProbeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndpointProbeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_nylon_ipc_proto_enumTypes[2].Descriptor()
}

func (EndpointProbeStatus) Type() protoreflect.EnumType {
	return &file_protocol_nylon_ipc_proto_enumTypes[2]
}

func (x EndpointProbeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndpointProbeStatus.Descriptor instead.
func (EndpointProbeStatus) EnumDescriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{2}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{0}
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ProbeRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{2}
}

type TraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceRequest) Reset() {
	*x = TraceRequest{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequest) ProtoMessage() {}

func (x *TraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequest.ProtoReflect.Descriptor instead.
func (*TraceRequest) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{3}
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{4}
}

func (x *Source) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Source) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type FD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seqno         uint32                 `protobuf:"varint,1,opt,name=seqno,proto3" json:"seqno,omitempty"`
	Metric        uint32                 `protobuf:"varint,2,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FD) Reset() {
	*x = FD{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FD) ProtoMessage() {}

func (x *FD) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FD.ProtoReflect.Descriptor instead.
func (*FD) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *FD) GetSeqno() uint32 {
	if x != nil {
		return x.Seqno
	}
	return 0
}

func (x *FD) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

type PubRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Fd            *FD                    `protobuf:"bytes,2,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubRoute) Reset() {
	*x = PubRoute{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubRoute) ProtoMessage() {}

func (x *PubRoute) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubRoute.ProtoReflect.Descriptor instead.
func (*PubRoute) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{6}
}

func (x *PubRoute) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PubRoute) GetFd() *FD {
	if x != nil {
		return x.Fd
	}
	return nil
}

type NeighRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubRoute      *PubRoute              `protobuf:"bytes,1,opt,name=pub_route,json=pubRoute,proto3" json:"pub_route,omitempty"`
	ExpireAtUnix  int64                  `protobuf:"varint,2,opt,name=expire_at_unix,json=expireAtUnix,proto3" json:"expire_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighRoute) Reset() {
	*x = NeighRoute{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighRoute) ProtoMessage() {}

func (x *NeighRoute) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighRoute.ProtoReflect.Descriptor instead.
func (*NeighRoute) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *NeighRoute) GetPubRoute() *PubRoute {
	if x != nil {
		return x.PubRoute
	}
	return nil
}

func (x *NeighRoute) GetExpireAtUnix() int64 {
	if x != nil {
		return x.ExpireAtUnix
	}
	return 0
}

type SelRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubRoute      *PubRoute              `protobuf:"bytes,1,opt,name=pub_route,json=pubRoute,proto3" json:"pub_route,omitempty"`
	Nh            string                 `protobuf:"bytes,2,opt,name=nh,proto3" json:"nh,omitempty"`
	ExpireAtUnix  int64                  `protobuf:"varint,3,opt,name=expire_at_unix,json=expireAtUnix,proto3" json:"expire_at_unix,omitempty"`
	RetractedBy   []string               `protobuf:"bytes,4,rep,name=retracted_by,json=retractedBy,proto3" json:"retracted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelRoute) Reset() {
	*x = SelRoute{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelRoute) ProtoMessage() {}

func (x *SelRoute) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelRoute.ProtoReflect.Descriptor instead.
func (*SelRoute) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{8}
}

func (x *SelRoute) GetPubRoute() *PubRoute {
	if x != nil {
		return x.PubRoute
	}
	return nil
}

func (x *SelRoute) GetNh() string {
	if x != nil {
		return x.Nh
	}
	return ""
}

func (x *SelRoute) GetExpireAtUnix() int64 {
	if x != nil {
		return x.ExpireAtUnix
	}
	return 0
}

func (x *SelRoute) GetRetractedBy() []string {
	if x != nil {
		return x.RetractedBy
	}
	return nil
}

type Advertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Metric        uint32                 `protobuf:"varint,3,opt,name=metric,proto3" json:"metric,omitempty"`
	ExpiryUnix    int64                  `protobuf:"varint,4,opt,name=expiry_unix,json=expiryUnix,proto3" json:"expiry_unix,omitempty"`
	PassiveHold   bool                   `protobuf:"varint,5,opt,name=passive_hold,json=passiveHold,proto3" json:"passive_hold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{9}
}

func (x *Advertisement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Advertisement) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Advertisement) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Advertisement) GetExpiryUnix() int64 {
	if x != nil {
		return x.ExpiryUnix
	}
	return 0
}

func (x *Advertisement) GetPassiveHold() bool {
	if x != nil {
		return x.PassiveHold
	}
	return false
}

type EndpointInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Address            string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Resolved           *string                `protobuf:"bytes,2,opt,name=resolved,proto3,oneof" json:"resolved,omitempty"`
	Active             bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	RemoteInit         bool                   `protobuf:"varint,4,opt,name=remote_init,json=remoteInit,proto3" json:"remote_init,omitempty"`
	Metric             uint32                 `protobuf:"varint,5,opt,name=metric,proto3" json:"metric,omitempty"`
	FilteredRttNs      int64                  `protobuf:"varint,7,opt,name=filtered_rtt_ns,json=filteredRttNs,proto3" json:"filtered_rtt_ns,omitempty"`
	StabilizedRttNs    int64                  `protobuf:"varint,8,opt,name=stabilized_rtt_ns,json=stabilizedRttNs,proto3" json:"stabilized_rtt_ns,omitempty"`
	LocalBindInterface string                 `protobuf:"bytes,10,opt,name=local_bind_interface,json=localBindInterface,proto3" json:"local_bind_interface,omitempty"`
	LocalBindSource    string                 `protobuf:"bytes,11,opt,name=local_bind_source,json=localBindSource,proto3" json:"local_bind_source,omitempty"`
	LossRate           float32                `protobuf:"fixed32,12,opt,name=loss_rate,json=lossRate,proto3" json:"loss_rate,omitempty"`
	// Excess one-way delay of this link relative to the neighbour's best link
	// in each direction (absolute one-way delays are unknowable without
	// synchronized clocks, but differences between links of the same
	// neighbour are exact). The preferred link in a direction shows 0; -1
	// when the link has not collected enough samples.
	OutExcessNs int64 `protobuf:"varint,13,opt,name=out_excess_ns,json=outExcessNs,proto3" json:"out_excess_ns,omitempty"`
	InExcessNs  int64 `protobuf:"varint,14,opt,name=in_excess_ns,json=inExcessNs,proto3" json:"in_excess_ns,omitempty"`
	// selected is true for the link this node currently sends on (the active
	// link with the lowest outbound delay + loss score).
	Selected      bool              `protobuf:"varint,15,opt,name=selected,proto3" json:"selected,omitempty"`
	Transport     EndpointTransport `protobuf:"varint,16,opt,name=transport,proto3,enum=proto.EndpointTransport" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointInfo) Reset() {
	*x = EndpointInfo{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointInfo) ProtoMessage() {}

func (x *EndpointInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointInfo.ProtoReflect.Descriptor instead.
func (*EndpointInfo) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{10}
}

func (x *EndpointInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EndpointInfo) GetResolved() string {
	if x != nil && x.Resolved != nil {
		return *x.Resolved
	}
	return ""
}

func (x *EndpointInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *EndpointInfo) GetRemoteInit() bool {
	if x != nil {
		return x.RemoteInit
	}
	return false
}

func (x *EndpointInfo) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *EndpointInfo) GetFilteredRttNs() int64 {
	if x != nil {
		return x.FilteredRttNs
	}
	return 0
}

func (x *EndpointInfo) GetStabilizedRttNs() int64 {
	if x != nil {
		return x.StabilizedRttNs
	}
	return 0
}

func (x *EndpointInfo) GetLocalBindInterface() string {
	if x != nil {
		return x.LocalBindInterface
	}
	return ""
}

func (x *EndpointInfo) GetLocalBindSource() string {
	if x != nil {
		return x.LocalBindSource
	}
	return ""
}

func (x *EndpointInfo) GetLossRate() float32 {
	if x != nil {
		return x.LossRate
	}
	return 0
}

func (x *EndpointInfo) GetOutExcessNs() int64 {
	if x != nil {
		return x.OutExcessNs
	}
	return 0
}

func (x *EndpointInfo) GetInExcessNs() int64 {
	if x != nil {
		return x.InExcessNs
	}
	return 0
}

func (x *EndpointInfo) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *EndpointInfo) GetTransport() EndpointTransport {
	if x != nil {
		return x.Transport
	}
	return EndpointTransport_UDP
}

type WireGuardPeerStats struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	LatestHandshakeUnix         int64                  `protobuf:"varint,1,opt,name=latest_handshake_unix,json=latestHandshakeUnix,proto3" json:"latest_handshake_unix,omitempty"`
	TxBytes                     uint64                 `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes                     uint64                 `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	PersistentKeepaliveInterval uint32                 `protobuf:"varint,4,opt,name=persistent_keepalive_interval,json=persistentKeepaliveInterval,proto3" json:"persistent_keepalive_interval,omitempty"`
	Endpoint                    *string                `protobuf:"bytes,5,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WireGuardPeerStats) Reset() {
	*x = WireGuardPeerStats{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardPeerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeerStats) ProtoMessage() {}

func (x *WireGuardPeerStats) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeerStats.ProtoReflect.Descriptor instead.
func (*WireGuardPeerStats) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{11}
}

func (x *WireGuardPeerStats) GetLatestHandshakeUnix() int64 {
	if x != nil {
		return x.LatestHandshakeUnix
	}
	return 0
}

func (x *WireGuardPeerStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *WireGuardPeerStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *WireGuardPeerStats) GetPersistentKeepaliveInterval() uint32 {
	if x != nil {
		return x.PersistentKeepaliveInterval
	}
	return 0
}

func (x *WireGuardPeerStats) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

type NeighbourInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PassiveClient bool                   `protobuf:"varint,3,opt,name=passive_client,json=passiveClient,proto3" json:"passive_client,omitempty"`
	Endpoints     []*EndpointInfo        `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Routes        []*NeighRoute          `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	Advertised    []*Advertisement       `protobuf:"bytes,6,rep,name=advertised,proto3" json:"advertised,omitempty"`
	Wireguard     *WireGuardPeerStats    `protobuf:"bytes,7,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	// link_cost is the single-hop cost towards this neighbour advertised to
	// the routing layer: the effective cycle latency (best outbound + best
	// inbound link, chosen independently per direction) penalized by the
	// coupled loss of the two selected links. Expressed in microseconds.
	LinkCost      uint32 `protobuf:"varint,8,opt,name=link_cost,json=linkCost,proto3" json:"link_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighbourInfo) Reset() {
	*x = NeighbourInfo{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighbourInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighbourInfo) ProtoMessage() {}

func (x *NeighbourInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighbourInfo.ProtoReflect.Descriptor instead.
func (*NeighbourInfo) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{12}
}

func (x *NeighbourInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NeighbourInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NeighbourInfo) GetPassiveClient() bool {
	if x != nil {
		return x.PassiveClient
	}
	return false
}

func (x *NeighbourInfo) GetEndpoints() []*EndpointInfo {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NeighbourInfo) GetRoutes() []*NeighRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NeighbourInfo) GetAdvertised() []*Advertisement {
	if x != nil {
		return x.Advertised
	}
	return nil
}

func (x *NeighbourInfo) GetWireguard() *WireGuardPeerStats {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

func (x *NeighbourInfo) GetLinkCost() uint32 {
	if x != nil {
		return x.LinkCost
	}
	return 0
}

type RouteTableEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Nh            string                 `protobuf:"bytes,2,opt,name=nh,proto3" json:"nh,omitempty"`
	Blackhole     bool                   `protobuf:"varint,3,opt,name=blackhole,proto3" json:"blackhole,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTableEntry) Reset() {
	*x = RouteTableEntry{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableEntry) ProtoMessage() {}

func (x *RouteTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableEntry.ProtoReflect.Descriptor instead.
func (*RouteTableEntry) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{13}
}

func (x *RouteTableEntry) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *RouteTableEntry) GetNh() string {
	if x != nil {
		return x.Nh
	}
	return ""
}

func (x *RouteTableEntry) GetBlackhole() bool {
	if x != nil {
		return x.Blackhole
	}
	return false
}

type RouteTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selected      []*SelRoute            `protobuf:"bytes,1,rep,name=selected,proto3" json:"selected,omitempty"`
	Forward       []*RouteTableEntry     `protobuf:"bytes,2,rep,name=forward,proto3" json:"forward,omitempty"`
	Exit          []*RouteTableEntry     `protobuf:"bytes,3,rep,name=exit,proto3" json:"exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTables) Reset() {
	*x = RouteTables{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTables) ProtoMessage() {}

func (x *RouteTables) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTables.ProtoReflect.Descriptor instead.
func (*RouteTables) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{14}
}

func (x *RouteTables) GetSelected() []*SelRoute {
	if x != nil {
		return x.Selected
	}
	return nil
}

func (x *RouteTables) GetForward() []*RouteTableEntry {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *RouteTables) GetExit() []*RouteTableEntry {
	if x != nil {
		return x.Exit
	}
	return nil
}

type SeqnoEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Seqno         uint32                 `protobuf:"varint,2,opt,name=seqno,proto3" json:"seqno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeqnoEntry) Reset() {
	*x = SeqnoEntry{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeqnoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeqnoEntry) ProtoMessage() {}

func (x *SeqnoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeqnoEntry.ProtoReflect.Descriptor instead.
func (*SeqnoEntry) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{15}
}

func (x *SeqnoEntry) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SeqnoEntry) GetSeqno() uint32 {
	if x != nil {
		return x.Seqno
	}
	return 0
}

type FeasibilityDistance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Fd            *FD                    `protobuf:"bytes,2,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeasibilityDistance) Reset() {
	*x = FeasibilityDistance{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeasibilityDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeasibilityDistance) ProtoMessage() {}

func (x *FeasibilityDistance) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeasibilityDistance.ProtoReflect.Descriptor instead.
func (*FeasibilityDistance) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{16}
}

func (x *FeasibilityDistance) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FeasibilityDistance) GetFd() *FD {
	if x != nil {
		return x.Fd
	}
	return nil
}

type NodeStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NeighbourCount        int32                  `protobuf:"varint,1,opt,name=neighbour_count,json=neighbourCount,proto3" json:"neighbour_count,omitempty"`
	ActiveEndpointCount   int32                  `protobuf:"varint,2,opt,name=active_endpoint_count,json=activeEndpointCount,proto3" json:"active_endpoint_count,omitempty"`
	SelectedRouteCount    int32                  `protobuf:"varint,3,opt,name=selected_route_count,json=selectedRouteCount,proto3" json:"selected_route_count,omitempty"`
	AdvertisedPrefixCount int32                  `protobuf:"varint,4,opt,name=advertised_prefix_count,json=advertisedPrefixCount,proto3" json:"advertised_prefix_count,omitempty"`
	TxBytes               uint64                 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes               uint64                 `protobuf:"varint,6,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{17}
}

func (x *NodeStats) GetNeighbourCount() int32 {
	if x != nil {
		return x.NeighbourCount
	}
	return 0
}

func (x *NodeStats) GetActiveEndpointCount() int32 {
	if x != nil {
		return x.ActiveEndpointCount
	}
	return 0
}

func (x *NodeStats) GetSelectedRouteCount() int32 {
	if x != nil {
		return x.SelectedRouteCount
	}
	return 0
}

func (x *NodeStats) GetAdvertisedPrefixCount() int32 {
	if x != nil {
		return x.AdvertisedPrefixCount
	}
	return 0
}

func (x *NodeStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NodeStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type NodeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Interface       string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	PublicKey       string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ListenPort      uint32                 `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	ConfigTimestamp int64                  `protobuf:"varint,5,opt,name=config_timestamp,json=configTimestamp,proto3" json:"config_timestamp,omitempty"`
	TraceEnabled    bool                   `protobuf:"varint,6,opt,name=trace_enabled,json=traceEnabled,proto3" json:"trace_enabled,omitempty"`
	Advertised      []*Advertisement       `protobuf:"bytes,7,rep,name=advertised,proto3" json:"advertised,omitempty"`
	Seqnos          []*SeqnoEntry          `protobuf:"bytes,8,rep,name=seqnos,proto3" json:"seqnos,omitempty"`
	Stats           *NodeStats             `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{18}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *NodeStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NodeStatus) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NodeStatus) GetConfigTimestamp() int64 {
	if x != nil {
		return x.ConfigTimestamp
	}
	return 0
}

func (x *NodeStatus) GetTraceEnabled() bool {
	if x != nil {
		return x.TraceEnabled
	}
	return false
}

func (x *NodeStatus) GetAdvertised() []*Advertisement {
	if x != nil {
		return x.Advertised
	}
	return nil
}

func (x *NodeStatus) GetSeqnos() []*SeqnoEntry {
	if x != nil {
		return x.Seqnos
	}
	return nil
}

func (x *NodeStatus) GetStats() *NodeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Node                 *NodeStatus            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Neighbours           []*NeighbourInfo       `protobuf:"bytes,2,rep,name=neighbours,proto3" json:"neighbours,omitempty"`
	Routes               *RouteTables           `protobuf:"bytes,3,opt,name=routes,proto3" json:"routes,omitempty"`
	FeasibilityDistances []*FeasibilityDistance `protobuf:"bytes,4,rep,name=feasibility_distances,json=feasibilityDistances,proto3" json:"feasibility_distances,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{19}
}

func (x *StatusResponse) GetNode() *NodeStatus {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *StatusResponse) GetNeighbours() []*NeighbourInfo {
	if x != nil {
		return x.Neighbours
	}
	return nil
}

func (x *StatusResponse) GetRoutes() *RouteTables {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *StatusResponse) GetFeasibilityDistances() []*FeasibilityDistance {
	if x != nil {
		return x.FeasibilityDistances
	}
	return nil
}

type EndpointProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Resolved      *string                `protobuf:"bytes,4,opt,name=resolved,proto3,oneof" json:"resolved,omitempty"`
	Status        EndpointProbeStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=proto.EndpointProbeStatus" json:"status,omitempty"`
	LatencyNs     int64                  `protobuf:"varint,6,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointProbeResult) Reset() {
	*x = EndpointProbeResult{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointProbeResult) ProtoMessage() {}

func (x *EndpointProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointProbeResult.ProtoReflect.Descriptor instead.
func (*EndpointProbeResult) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{20}
}

func (x *EndpointProbeResult) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EndpointProbeResult) GetResolved() string {
	if x != nil && x.Resolved != nil {
		return *x.Resolved
	}
	return ""
}

func (x *EndpointProbeResult) GetStatus() EndpointProbeStatus {
	if x != nil {
		return x.Status
	}
	return EndpointProbeStatus_ENDPOINT_PROBE_STATUS_UNSPECIFIED
}

func (x *EndpointProbeResult) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EndpointProbeResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{21}
}

func (x *ProbeResponse) GetResults() []*EndpointProbeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        ReloadResult           `protobuf:"varint,1,opt,name=result,proto3,enum=proto.ReloadResult" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{22}
}

func (x *ReloadResponse) GetResult() ReloadResult {
	if x != nil {
		return x.Result
	}
	return ReloadResult_NOOP
}

func (x *ReloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{23}
}

func (x *TraceEvent) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type IpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*IpcRequest_Status
	//	*IpcRequest_Probe
	//	*IpcRequest_Reload
	//	*IpcRequest_Trace
	Request       isIpcRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcRequest) Reset() {
	*x = IpcRequest{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcRequest) ProtoMessage() {}

func (x *IpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcRequest.ProtoReflect.Descriptor instead.
func (*IpcRequest) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{24}
}

func (x *IpcRequest) GetRequest() isIpcRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *IpcRequest) GetStatus() *StatusRequest {
	if x != nil {
		if x, ok := x.Request.(*IpcRequest_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *IpcRequest) GetProbe() *ProbeRequest {
	if x != nil {
		if x, ok := x.Request.(*IpcRequest_Probe); ok {
			return x.Probe
		}
	}
	return nil
}

func (x *IpcRequest) GetReload() *ReloadRequest {
	if x != nil {
		if x, ok := x.Request.(*IpcRequest_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *IpcRequest) GetTrace() *TraceRequest {
	if x != nil {
		if x, ok := x.Request.(*IpcRequest_Trace); ok {
			return x.Trace
		}
	}
	return nil
}

type isIpcRequest_Request interface {
	isIpcRequest_Request()
}

type IpcRequest_Status struct {
	Status *StatusRequest `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type IpcRequest_Probe struct {
	Probe *ProbeRequest `protobuf:"bytes,2,opt,name=probe,proto3,oneof"`
}

type IpcRequest_Reload struct {
	Reload *ReloadRequest `protobuf:"bytes,3,opt,name=reload,proto3,oneof"`
}

type IpcRequest_Trace struct {
	Trace *TraceRequest `protobuf:"bytes,4,opt,name=trace,proto3,oneof"`
}

func (*IpcRequest_Status) isIpcRequest_Request() {}

func (*IpcRequest_Probe) isIpcRequest_Request() {}

func (*IpcRequest_Reload) isIpcRequest_Request() {}

func (*IpcRequest_Trace) isIpcRequest_Request() {}

type IpcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*IpcResponse_Status
	//	*IpcResponse_Probe
	//	*IpcResponse_Reload
	//	*IpcResponse_Trace
	Response      isIpcResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcResponse) Reset() {
	*x = IpcResponse{}
	mi := &file_protocol_nylon_ipc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcResponse) ProtoMessage() {}

func (x *IpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_ipc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcResponse.ProtoReflect.Descriptor instead.
func (*IpcResponse) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_ipc_proto_rawDescGZIP(), []int{25}
}

func (x *IpcResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IpcResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IpcResponse) GetResponse() isIpcResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *IpcResponse) GetStatus() *StatusResponse {
	if x != nil {
		if x, ok := x.Response.(*IpcResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *IpcResponse) GetProbe() *ProbeResponse {
	if x != nil {
		if x, ok := x.Response.(*IpcResponse_Probe); ok {
			return x.Probe
		}
	}
	return nil
}

func (x *IpcResponse) GetReload() *ReloadResponse {
	if x != nil {
		if x, ok := x.Response.(*IpcResponse_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *IpcResponse) GetTrace() *TraceEvent {
	if x != nil {
		if x, ok := x.Response.(*IpcResponse_Trace); ok {
			return x.Trace
		}
	}
	return nil
}

type isIpcResponse_Response interface {
	isIpcResponse_Response()
}

type IpcResponse_Status struct {
	Status *StatusResponse `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type IpcResponse_Probe struct {
	Probe *ProbeResponse `protobuf:"bytes,4,opt,name=probe,proto3,oneof"`
}

type IpcResponse_Reload struct {
	Reload *ReloadResponse `protobuf:"bytes,5,opt,name=reload,proto3,oneof"`
}

type IpcResponse_Trace struct {
	Trace *TraceEvent `protobuf:"bytes,6,opt,name=trace,proto3,oneof"`
}

func (*IpcResponse_Status) isIpcResponse_Response() {}

func (*IpcResponse_Probe) isIpcResponse_Response() {}

func (*IpcResponse_Reload) isIpcResponse_Response() {}

func (*IpcResponse_Trace) isIpcResponse_Response() {}

var File_protocol_nylon_ipc_proto protoreflect.FileDescriptor

const file_protocol_nylon_ipc_proto_rawDesc = "" +
	"\n" +
	"\x18protocol/nylon_ipc.proto\x12\x05proto\"\x0f\n" +
	"\rStatusRequest\"F\n" +
	"\fProbeRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"\x0f\n" +
	"\rReloadRequest\"\x0e\n" +
	"\fTraceRequest\"9\n" +
	"\x06Source\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\"2\n" +
	"\x02FD\x12\x14\n" +
	"\x05seqno\x18\x01 \x01(\rR\x05seqno\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\rR\x06metric\"L\n" +
	"\bPubRoute\x12%\n" +
	"\x06source\x18\x01 \x01(\v2\r.proto.SourceR\x06source\x12\x19\n" +
	"\x02fd\x18\x02 \x01(\v2\t.proto.FDR\x02fd\"`\n" +
	"\n" +
	"NeighRoute\x12,\n" +
	"\tpub_route\x18\x01 \x01(\v2\x0f.proto.PubRouteR\bpubRoute\x12$\n" +
	"\x0eexpire_at_unix\x18\x02 \x01(\x03R\fexpireAtUnix\"\x91\x01\n" +
	"\bSelRoute\x12,\n" +
	"\tpub_route\x18\x01 \x01(\v2\x0f.proto.PubRouteR\bpubRoute\x12\x0e\n" +
	"\x02nh\x18\x02 \x01(\tR\x02nh\x12$\n" +
	"\x0eexpire_at_unix\x18\x03 \x01(\x03R\fexpireAtUnix\x12!\n" +
	"\fretracted_by\x18\x04 \x03(\tR\vretractedBy\"\x9c\x01\n" +
	"\rAdvertisement\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\rR\x06metric\x12\x1f\n" +
	"\vexpiry_unix\x18\x04 \x01(\x03R\n" +
	"expiryUnix\x12!\n" +
	"\fpassive_hold\x18\x05 \x01(\bR\vpassiveHold\"\x90\x04\n" +
	"\fEndpointInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\bresolved\x18\x02 \x01(\tH\x00R\bresolved\x88\x01\x01\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1f\n" +
	"\vremote_init\x18\x04 \x01(\bR\n" +
	"remoteInit\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\rR\x06metric\x12&\n" +
	"\x0ffiltered_rtt_ns\x18\a \x01(\x03R\rfilteredRttNs\x12*\n" +
	"\x11stabilized_rtt_ns\x18\b \x01(\x03R\x0fstabilizedRttNs\x120\n" +
	"\x14local_bind_interface\x18\n" +
	" \x01(\tR\x12localBindInterface\x12*\n" +
	"\x11local_bind_source\x18\v \x01(\tR\x0flocalBindSource\x12\x1b\n" +
	"\tloss_rate\x18\f \x01(\x02R\blossRate\x12\"\n" +
	"\rout_excess_ns\x18\r \x01(\x03R\voutExcessNs\x12 \n" +
	"\fin_excess_ns\x18\x0e \x01(\x03R\n" +
	"inExcessNs\x12\x1a\n" +
	"\bselected\x18\x0f \x01(\bR\bselected\x126\n" +
	"\ttransport\x18\x10 \x01(\x0e2\x18.proto.EndpointTransportR\ttransportB\v\n" +
	"\t_resolved\"\xf0\x01\n" +
	"\x12WireGuardPeerStats\x122\n" +
	"\x15latest_handshake_unix\x18\x01 \x01(\x03R\x13latestHandshakeUnix\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12B\n" +
	"\x1dpersistent_keepalive_interval\x18\x04 \x01(\rR\x1bpersistentKeepaliveInterval\x12\x1f\n" +
	"\bendpoint\x18\x05 \x01(\tH\x00R\bendpoint\x88\x01\x01B\v\n" +
	"\t_endpoint\"\xd8\x02\n" +
	"\rNeighbourInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12%\n" +
	"\x0epassive_client\x18\x03 \x01(\bR\rpassiveClient\x121\n" +
	"\tendpoints\x18\x04 \x03(\v2\x13.proto.EndpointInfoR\tendpoints\x12)\n" +
	"\x06routes\x18\x05 \x03(\v2\x11.proto.NeighRouteR\x06routes\x124\n" +
	"\n" +
	"advertised\x18\x06 \x03(\v2\x14.proto.AdvertisementR\n" +
	"advertised\x127\n" +
	"\twireguard\x18\a \x01(\v2\x19.proto.WireGuardPeerStatsR\twireguard\x12\x1b\n" +
	"\tlink_cost\x18\b \x01(\rR\blinkCost\"W\n" +
	"\x0fRouteTableEntry\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x0e\n" +
	"\x02nh\x18\x02 \x01(\tR\x02nh\x12\x1c\n" +
	"\tblackhole\x18\x03 \x01(\bR\tblackhole\"\x98\x01\n" +
	"\vRouteTables\x12+\n" +
	"\bselected\x18\x01 \x03(\v2\x0f.proto.SelRouteR\bselected\x120\n" +
	"\aforward\x18\x02 \x03(\v2\x16.proto.RouteTableEntryR\aforward\x12*\n" +
	"\x04exit\x18\x03 \x03(\v2\x16.proto.RouteTableEntryR\x04exit\":\n" +
	"\n" +
	"SeqnoEntry\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05seqno\x18\x02 \x01(\rR\x05seqno\"W\n" +
	"\x13FeasibilityDistance\x12%\n" +
	"\x06source\x18\x01 \x01(\v2\r.proto.SourceR\x06source\x12\x19\n" +
	"\x02fd\x18\x02 \x01(\v2\t.proto.FDR\x02fd\"\x88\x02\n" +
	"\tNodeStats\x12'\n" +
	"\x0fneighbour_count\x18\x01 \x01(\x05R\x0eneighbourCount\x122\n" +
	"\x15active_endpoint_count\x18\x02 \x01(\x05R\x13activeEndpointCount\x120\n" +
	"\x14selected_route_count\x18\x03 \x01(\x05R\x12selectedRouteCount\x126\n" +
	"\x17advertised_prefix_count\x18\x04 \x01(\x05R\x15advertisedPrefixCount\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x06 \x01(\x04R\arxBytes\"\xdc\x02\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\rR\n" +
	"listenPort\x12)\n" +
	"\x10config_timestamp\x18\x05 \x01(\x03R\x0fconfigTimestamp\x12#\n" +
	"\rtrace_enabled\x18\x06 \x01(\bR\ftraceEnabled\x124\n" +
	"\n" +
	"advertised\x18\a \x03(\v2\x14.proto.AdvertisementR\n" +
	"advertised\x12)\n" +
	"\x06seqnos\x18\b \x03(\v2\x11.proto.SeqnoEntryR\x06seqnos\x12&\n" +
	"\x05stats\x18\t \x01(\v2\x10.proto.NodeStatsR\x05stats\"\xea\x01\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.proto.NodeStatusR\x04node\x124\n" +
	"\n" +
	"neighbours\x18\x02 \x03(\v2\x14.proto.NeighbourInfoR\n" +
	"neighbours\x12*\n" +
	"\x06routes\x18\x03 \x01(\v2\x12.proto.RouteTablesR\x06routes\x12O\n" +
	"\x15feasibility_distances\x18\x04 \x03(\v2\x1a.proto.FeasibilityDistanceR\x14feasibilityDistances\"\xb0\x01\n" +
	"\x13EndpointProbeResult\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\bresolved\x18\x04 \x01(\tH\x00R\bresolved\x88\x01\x01\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.proto.EndpointProbeStatusR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x06 \x01(\x03R\tlatencyNsB\v\n" +
	"\t_resolved\"E\n" +
	"\rProbeResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.proto.EndpointProbeResultR\aresults\"W\n" +
	"\x0eReloadResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.proto.ReloadResultR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\n" +
	"TraceEvent\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"\xd1\x01\n" +
	"\n" +
	"IpcRequest\x12.\n" +
	"\x06status\x18\x01 \x01(\v2\x14.proto.StatusRequestH\x00R\x06status\x12+\n" +
	"\x05probe\x18\x02 \x01(\v2\x13.proto.ProbeRequestH\x00R\x05probe\x12.\n" +
	"\x06reload\x18\x03 \x01(\v2\x14.proto.ReloadRequestH\x00R\x06reload\x12+\n" +
	"\x05trace\x18\x04 \x01(\v2\x13.proto.TraceRequestH\x00R\x05traceB\t\n" +
	"\arequest\"\xfa\x01\n" +
	"\vIpcResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12/\n" +
	"\x06status\x18\x03 \x01(\v2\x15.proto.StatusResponseH\x00R\x06status\x12,\n" +
	"\x05probe\x18\x04 \x01(\v2\x14.proto.ProbeResponseH\x00R\x05probe\x12/\n" +
	"\x06reload\x18\x05 \x01(\v2\x15.proto.ReloadResponseH\x00R\x06reload\x12)\n" +
	"\x05trace\x18\x06 \x01(\v2\x11.proto.TraceEventH\x00R\x05traceB\n" +
	"\n" +
	"\bresponse*I\n" +
	"\fReloadResult\x12\b\n" +
	"\x04NOOP\x10\x00\x12\v\n" +
	"\aAPPLIED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\x14\n" +
	"\x10RESTART_REQUIRED\x10\x03**\n" +
	"\x11EndpointTransport\x12\a\n" +
	"\x03UDP\x10\x00\x12\f\n" +
	"\bFAKE_TCP\x10\x01*\xb5\x01\n" +
	"\x13EndpointProbeStatus\x12%\n" +
	"!ENDPOINT_PROBE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ENDPOINT_PROBE_REPLIED\x10\x01\x12\x1a\n" +
	"\x16ENDPOINT_PROBE_TIMEOUT\x10\x02\x12\x1d\n" +
	"\x19ENDPOINT_PROBE_SEND_ERROR\x10\x03\x12 \n" +
	"\x1cENDPOINT_PROBE_RESOLVE_ERROR\x10\x04B\vZ\tprotocol/b\x06proto3"

var (
	file_protocol_nylon_ipc_proto_rawDescOnce sync.Once
	file_protocol_nylon_ipc_proto_rawDescData []byte
)

func file_protocol_nylon_ipc_proto_rawDescGZIP() []byte {
	file_protocol_nylon_ipc_proto_rawDescOnce.Do(func() {
		file_protocol_nylon_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_nylon_ipc_proto_rawDesc), len(file_protocol_nylon_ipc_proto_rawDesc)))
	})
	return file_protocol_nylon_ipc_proto_rawDescData
}

var file_protocol_nylon_ipc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protocol_nylon_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_protocol_nylon_ipc_proto_goTypes = []any{
	(ReloadResult)(0),           // 0: proto.ReloadResult
	(EndpointTransport)(0),      // 1: proto.EndpointTransport
	(EndpointProbeStatus)(0),    // 2: proto.EndpointProbeStatus
	(*StatusRequest)(nil),       // 3: proto.StatusRequest
	(*ProbeRequest)(nil),        // 4: proto.ProbeRequest
	(*ReloadRequest)(nil),       // 5: proto.ReloadRequest
	(*TraceRequest)(nil),        // 6: proto.TraceRequest
	(*Source)(nil),              // 7: proto.Source
	(*FD)(nil),                  // 8: proto.FD
	(*PubRoute)(nil),            // 9: proto.PubRoute
	(*NeighRoute)(nil),          // 10: proto.NeighRoute
	(*SelRoute)(nil),            // 11: proto.SelRoute
	(*Advertisement)(nil),       // 12: proto.Advertisement
	(*EndpointInfo)(nil),        // 13: proto.EndpointInfo
	(*WireGuardPeerStats)(nil),  // 14: proto.WireGuardPeerStats
	(*NeighbourInfo)(nil),       // 15: proto.NeighbourInfo
	(*RouteTableEntry)(nil),     // 16: proto.RouteTableEntry
	(*RouteTables)(nil),         // 17: proto.RouteTables
	(*SeqnoEntry)(nil),          // 18: proto.SeqnoEntry
	(*FeasibilityDistance)(nil), // 19: proto.FeasibilityDistance
	(*NodeStats)(nil),           // 20: proto.NodeStats
	(*NodeStatus)(nil),          // 21: proto.NodeStatus
	(*StatusResponse)(nil),      // 22: proto.StatusResponse
	(*EndpointProbeResult)(nil), // 23: proto.EndpointProbeResult
	(*ProbeResponse)(nil),       // 24: proto.ProbeResponse
	(*ReloadResponse)(nil),      // 25: proto.ReloadResponse
	(*TraceEvent)(nil),          // 26: proto.TraceEvent
	(*IpcRequest)(nil),          // 27: proto.IpcRequest
	(*IpcResponse)(nil),         // 28: proto.IpcResponse
}
var file_protocol_nylon_ipc_proto_depIdxs = []int32{
	7,  // 0: proto.PubRoute.source:type_name -> proto.Source
	8,  // 1: proto.PubRoute.fd:type_name -> proto.FD
	9,  // 2: proto.NeighRoute.pub_route:type_name -> proto.PubRoute
	9,  // 3: proto.SelRoute.pub_route:type_name -> proto.PubRoute
	1,  // 4: proto.EndpointInfo.transport:type_name -> proto.EndpointTransport
	13, // 5: proto.NeighbourInfo.endpoints:type_name -> proto.EndpointInfo
	10, // 6: proto.NeighbourInfo.routes:type_name -> proto.NeighRoute
	12, // 7: proto.NeighbourInfo.advertised:type_name -> proto.Advertisement
	14, // 8: proto.NeighbourInfo.wireguard:type_name -> proto.WireGuardPeerStats
	11, // 9: proto.RouteTables.selected:type_name -> proto.SelRoute
	16, // 10: proto.RouteTables.forward:type_name -> proto.RouteTableEntry
	16, // 11: proto.RouteTables.exit:type_name -> proto.RouteTableEntry
	7,  // 12: proto.FeasibilityDistance.source:type_name -> proto.Source
	8,  // 13: proto.FeasibilityDistance.fd:type_name -> proto.FD
	12, // 14: proto.NodeStatus.advertised:type_name -> proto.Advertisement
	18, // 15: proto.NodeStatus.seqnos:type_name -> proto.SeqnoEntry
	20, // 16: proto.NodeStatus.stats:type_name -> proto.NodeStats
	21, // 17: proto.StatusResponse.node:type_name -> proto.NodeStatus
	15, // 18: proto.StatusResponse.neighbours:type_name -> proto.NeighbourInfo
	17, // 19: proto.StatusResponse.routes:type_name -> proto.RouteTables
	19, // 20: proto.StatusResponse.feasibility_distances:type_name -> proto.FeasibilityDistance
	2,  // 21: proto.EndpointProbeResult.status:type_name -> proto.EndpointProbeStatus
	23, // 22: proto.ProbeResponse.results:type_name -> proto.EndpointProbeResult
	0,  // 23: proto.ReloadResponse.result:type_name -> proto.ReloadResult
	3,  // 24: proto.IpcRequest.status:type_name -> proto.StatusRequest
	4,  // 25: proto.IpcRequest.probe:type_name -> proto.ProbeRequest
	5,  // 26: proto.IpcRequest.reload:type_name -> proto.ReloadRequest
	6,  // 27: proto.IpcRequest.trace:type_name -> proto.TraceRequest
	22, // 28: proto.IpcResponse.status:type_name -> proto.StatusResponse
	24, // 29: proto.IpcResponse.probe:type_name -> proto.ProbeResponse
	25, // 30: proto.IpcResponse.reload:type_name -> proto.ReloadResponse
	26, // 31: proto.IpcResponse.trace:type_name -> proto.TraceEvent
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_protocol_nylon_ipc_proto_init() }
func file_protocol_nylon_ipc_proto_init() {
	if File_protocol_nylon_ipc_proto != nil {
		return
	}
	file_protocol_nylon_ipc_proto_msgTypes[10].OneofWrappers = []any{}
	file_protocol_nylon_ipc_proto_msgTypes[11].OneofWrappers = []any{}
	file_protocol_nylon_ipc_proto_msgTypes[20].OneofWrappers = []any{}
	file_protocol_nylon_ipc_proto_msgTypes[24].OneofWrappers = []any{
		(*IpcRequest_Status)(nil),
		(*IpcRequest_Probe)(nil),
		(*IpcRequest_Reload)(nil),
		(*IpcRequest_Trace)(nil),
	}
	file_protocol_nylon_ipc_proto_msgTypes[25].OneofWrappers = []any{
		(*IpcResponse_Status)(nil),
		(*IpcResponse_Probe)(nil),
		(*IpcResponse_Reload)(nil),
		(*IpcResponse_Trace)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_nylon_ipc_proto_rawDesc), len(file_protocol_nylon_ipc_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_nylon_ipc_proto_goTypes,
		DependencyIndexes: file_protocol_nylon_ipc_proto_depIdxs,
		EnumInfos:         file_protocol_nylon_ipc_proto_enumTypes,
		MessageInfos:      file_protocol_nylon_ipc_proto_msgTypes,
	}.Build()
	File_protocol_nylon_ipc_proto = out.File
	file_protocol_nylon_ipc_proto_goTypes = nil
	file_protocol_nylon_ipc_proto_depIdxs = nil
}
