// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protocol/nylon.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packets       []*Ny                  `protobuf:"bytes,1,rep,name=Packets,proto3" json:"Packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportBundle) Reset() {
	*x = TransportBundle{}
	mi := &file_protocol_nylon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportBundle) ProtoMessage() {}

func (x *TransportBundle) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportBundle.ProtoReflect.Descriptor instead.
func (*TransportBundle) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_proto_rawDescGZIP(), []int{0}
}

func (x *TransportBundle) GetPackets() []*Ny {
	if x != nil {
		return x.Packets
	}
	return nil
}

type Ny struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Ny_RouteOp
	//	*Ny_SeqnoRequestOp
	//	*Ny_ProbeOp
	//	*Ny_AckRetractOp
	Type          isNy_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ny) Reset() {
	*x = Ny{}
	mi := &file_protocol_nylon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ny) ProtoMessage() {}

func (x *Ny) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ny.ProtoReflect.Descriptor instead.
func (*Ny) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_proto_rawDescGZIP(), []int{1}
}

func (x *Ny) GetType() isNy_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Ny) GetRouteOp() *Ny_Update {
	if x != nil {
		if x, ok := x.Type.(*Ny_RouteOp); ok {
			return x.RouteOp
		}
	}
	return nil
}

func (x *Ny) GetSeqnoRequestOp() *Ny_SeqnoRequest {
	if x != nil {
		if x, ok := x.Type.(*Ny_SeqnoRequestOp); ok {
			return x.SeqnoRequestOp
		}
	}
	return nil
}

func (x *Ny) GetProbeOp() *Ny_Probe {
	if x != nil {
		if x, ok := x.Type.(*Ny_ProbeOp); ok {
			return x.ProbeOp
		}
	}
	return nil
}

func (x *Ny) GetAckRetractOp() *Ny_AckRetract {
	if x != nil {
		if x, ok := x.Type.(*Ny_AckRetractOp); ok {
			return x.AckRetractOp
		}
	}
	return nil
}

type isNy_Type interface {
	isNy_Type()
}

type Ny_RouteOp struct {
	RouteOp *Ny_Update `protobuf:"bytes,1,opt,name=RouteOp,proto3,oneof"`
}

type Ny_SeqnoRequestOp struct {
	SeqnoRequestOp *Ny_SeqnoRequest `protobuf:"bytes,2,opt,name=SeqnoRequestOp,proto3,oneof"`
}

type Ny_ProbeOp struct {
	ProbeOp *Ny_Probe `protobuf:"bytes,3,opt,name=ProbeOp,proto3,oneof"`
}

type Ny_AckRetractOp struct {
	AckRetractOp *Ny_AckRetract `protobuf:"bytes,4,opt,name=AckRetractOp,proto3,oneof"`
}

func (*Ny_RouteOp) isNy_Type() {}

func (*Ny_SeqnoRequestOp) isNy_Type() {}

func (*Ny_ProbeOp) isNy_Type() {}

func (*Ny_AckRetractOp) isNy_Type() {}

type Ny_Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=RouterId,proto3" json:"RouterId,omitempty"`
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	Seqno         uint32                 `protobuf:"varint,3,opt,name=Seqno,proto3" json:"Seqno,omitempty"`
	Metric        uint32                 `protobuf:"varint,4,opt,name=Metric,proto3" json:"Metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ny_Update) Reset() {
	*x = Ny_Update{}
	mi := &file_protocol_nylon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ny_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ny_Update) ProtoMessage() {}

func (x *Ny_Update) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ny_Update.ProtoReflect.Descriptor instead.
func (*Ny_Update) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Ny_Update) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Ny_Update) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *Ny_Update) GetSeqno() uint32 {
	if x != nil {
		return x.Seqno
	}
	return 0
}

func (x *Ny_Update) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

type Ny_AckRetract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ny_AckRetract) Reset() {
	*x = Ny_AckRetract{}
	mi := &file_protocol_nylon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ny_AckRetract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ny_AckRetract) ProtoMessage() {}

func (x *Ny_AckRetract) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ny_AckRetract.ProtoReflect.Descriptor instead.
func (*Ny_AckRetract) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Ny_AckRetract) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type Ny_SeqnoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=RouterId,proto3" json:"RouterId,omitempty"`
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	Seqno         uint32                 `protobuf:"varint,3,opt,name=Seqno,proto3" json:"Seqno,omitempty"`
	HopCount      uint32                 `protobuf:"varint,4,opt,name=HopCount,proto3" json:"HopCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ny_SeqnoRequest) Reset() {
	*x = Ny_SeqnoRequest{}
	mi := &file_protocol_nylon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ny_SeqnoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ny_SeqnoRequest) ProtoMessage() {}

func (x *Ny_SeqnoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ny_SeqnoRequest.ProtoReflect.Descriptor instead.
func (*Ny_SeqnoRequest) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Ny_SeqnoRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Ny_SeqnoRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *Ny_SeqnoRequest) GetSeqno() uint32 {
	if x != nil {
		return x.Seqno
	}
	return 0
}

func (x *Ny_SeqnoRequest) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

// Probe implements RFC 9616-style (Babel Timestamp sub-TLV) delay
// measurement with relative timestamps. Every probe carries the sender's
// transmit timestamp; whenever the sender has previously heard a probe on
// the same link it also echoes that probe's timestamps. From a single
// received probe a node can derive the *relative* one-way delay of the
// inbound direction (local rx time - peer tx time, which embeds the
// unknown clock offset between the two nodes), and from the echo it can
// derive the relative one-way delay of the outbound direction as measured
// by the peer. Clock offsets cancel when the two directions are combined
// (RTT) or when links to the same peer are compared against each other,
// which is exactly what the router needs.
type Ny_Probe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transmit timestamp of this probe, in nanoseconds on the sender's
	// monotonic clock. The epoch is arbitrary (per-process), so only
	// differences between timestamps from the same sender are meaningful.
	TxTs int64 `protobuf:"varint,3,opt,name=TxTs,proto3" json:"TxTs,omitempty"`
	// Reply probes (pongs) are sent immediately in response to a non-reply
	// probe and are never answered themselves.
	Reply bool `protobuf:"varint,4,opt,name=Reply,proto3" json:"Reply,omitempty"`
	// LinkId identifies the sender's local link (endpoint) state. A reply
	// copies the value into ReplyLinkId so the original sender can attribute
	// the reply to the exact link it probed, even when several links share a
	// remote address or the reply source address was rewritten by a NAT.
	LinkId      uint64 `protobuf:"varint,5,opt,name=LinkId,proto3" json:"LinkId,omitempty"`
	ReplyLinkId uint64 `protobuf:"varint,6,opt,name=ReplyLinkId,proto3" json:"ReplyLinkId,omitempty"`
	// Echo of the most recent probe received from the peer on this link:
	// OriginTxTs is that probe's TxTs (on the peer's clock) and OriginRxTs
	// is the local time it was received (on the sender's clock). Combined
	// with TxTs and the receive time of this probe, the peer can compute the
	// outbound relative one-way delay (OriginRxTs - OriginTxTs) and the
	// offset-free RTT (rx - OriginTxTs) - (TxTs - OriginRxTs), which
	// excludes the time this node held the echo.
	OriginTxTs *int64 `protobuf:"varint,7,opt,name=OriginTxTs,proto3,oneof" json:"OriginTxTs,omitempty"`
	OriginRxTs *int64 `protobuf:"varint,8,opt,name=OriginRxTs,proto3,oneof" json:"OriginRxTs,omitempty"`
	// Discovery marks the initial authenticated probe for a LAN-discovered
	// candidate. Receivers use the packet's actual ingress interface to keep
	// that link separate from unbound configured endpoints.
	Discovery     bool `protobuf:"varint,9,opt,name=Discovery,proto3" json:"Discovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ny_Probe) Reset() {
	*x = Ny_Probe{}
	mi := &file_protocol_nylon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ny_Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ny_Probe) ProtoMessage() {}

func (x *Ny_Probe) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_nylon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ny_Probe.ProtoReflect.Descriptor instead.
func (*Ny_Probe) Descriptor() ([]byte, []int) {
	return file_protocol_nylon_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Ny_Probe) GetTxTs() int64 {
	if x != nil {
		return x.TxTs
	}
	return 0
}

func (x *Ny_Probe) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

func (x *Ny_Probe) GetLinkId() uint64 {
	if x != nil {
		return x.LinkId
	}
	return 0
}

func (x *Ny_Probe) GetReplyLinkId() uint64 {
	if x != nil {
		return x.ReplyLinkId
	}
	return 0
}

func (x *Ny_Probe) GetOriginTxTs() int64 {
	if x != nil && x.OriginTxTs != nil {
		return *x.OriginTxTs
	}
	return 0
}

func (x *Ny_Probe) GetOriginRxTs() int64 {
	if x != nil && x.OriginRxTs != nil {
		return *x.OriginRxTs
	}
	return 0
}

func (x *Ny_Probe) GetDiscovery() bool {
	if x != nil {
		return x.Discovery
	}
	return false
}

var File_protocol_nylon_proto protoreflect.FileDescriptor

const file_protocol_nylon_proto_rawDesc = "" +
	"\n" +
	"\x14protocol/nylon.proto\x12\x05proto\"6\n" +
	"\x0fTransportBundle\x12#\n" +
	"\aPackets\x18\x01 \x03(\v2\t.proto.NyR\aPackets\"\xed\x05\n" +
	"\x02Ny\x12,\n" +
	"\aRouteOp\x18\x01 \x01(\v2\x10.proto.Ny.UpdateH\x00R\aRouteOp\x12@\n" +
	"\x0eSeqnoRequestOp\x18\x02 \x01(\v2\x16.proto.Ny.SeqnoRequestH\x00R\x0eSeqnoRequestOp\x12+\n" +
	"\aProbeOp\x18\x03 \x01(\v2\x0f.proto.Ny.ProbeH\x00R\aProbeOp\x12:\n" +
	"\fAckRetractOp\x18\x04 \x01(\v2\x14.proto.Ny.AckRetractH\x00R\fAckRetractOp\x1aj\n" +
	"\x06Update\x12\x1a\n" +
	"\bRouterId\x18\x01 \x01(\tR\bRouterId\x12\x16\n" +
	"\x06Prefix\x18\x02 \x01(\fR\x06Prefix\x12\x14\n" +
	"\x05Seqno\x18\x03 \x01(\rR\x05Seqno\x12\x16\n" +
	"\x06Metric\x18\x04 \x01(\rR\x06Metric\x1a$\n" +
	"\n" +
	"AckRetract\x12\x16\n" +
	"\x06Prefix\x18\x01 \x01(\fR\x06Prefix\x1at\n" +
	"\fSeqnoRequest\x12\x1a\n" +
	"\bRouterId\x18\x01 \x01(\tR\bRouterId\x12\x16\n" +
	"\x06Prefix\x18\x02 \x01(\fR\x06Prefix\x12\x14\n" +
	"\x05Seqno\x18\x03 \x01(\rR\x05Seqno\x12\x1a\n" +
	"\bHopCount\x18\x04 \x01(\rR\bHopCount\x1a\xfd\x01\n" +
	"\x05Probe\x12\x12\n" +
	"\x04TxTs\x18\x03 \x01(\x03R\x04TxTs\x12\x14\n" +
	"\x05Reply\x18\x04 \x01(\bR\x05Reply\x12\x16\n" +
	"\x06LinkId\x18\x05 \x01(\x04R\x06LinkId\x12 \n" +
	"\vReplyLinkId\x18\x06 \x01(\x04R\vReplyLinkId\x12#\n" +
	"\n" +
	"OriginTxTs\x18\a \x01(\x03H\x00R\n" +
	"OriginTxTs\x88\x01\x01\x12#\n" +
	"\n" +
	"OriginRxTs\x18\b \x01(\x03H\x01R\n" +
	"OriginRxTs\x88\x01\x01\x12\x1c\n" +
	"\tDiscovery\x18\t \x01(\bR\tDiscoveryB\r\n" +
	"\v_OriginTxTsB\r\n" +
	"\v_OriginRxTsJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03B\x06\n" +
	"\x04typeB\vZ\tprotocol/b\x06proto3"

var (
	file_protocol_nylon_proto_rawDescOnce sync.Once
	file_protocol_nylon_proto_rawDescData []byte
)

func file_protocol_nylon_proto_rawDescGZIP() []byte {
	file_protocol_nylon_proto_rawDescOnce.Do(func() {
		file_protocol_nylon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_nylon_proto_rawDesc), len(file_protocol_nylon_proto_rawDesc)))
	})
	return file_protocol_nylon_proto_rawDescData
}

var file_protocol_nylon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protocol_nylon_proto_goTypes = []any{
	(*TransportBundle)(nil), // 0: proto.TransportBundle
	(*Ny)(nil),              // 1: proto.Ny
	(*Ny_Update)(nil),       // 2: proto.Ny.Update
	(*Ny_AckRetract)(nil),   // 3: proto.Ny.AckRetract
	(*Ny_SeqnoRequest)(nil), // 4: proto.Ny.SeqnoRequest
	(*Ny_Probe)(nil),        // 5: proto.Ny.Probe
}
var file_protocol_nylon_proto_depIdxs = []int32{
	1, // 0: proto.TransportBundle.Packets:type_name -> proto.Ny
	2, // 1: proto.Ny.RouteOp:type_name -> proto.Ny.Update
	4, // 2: proto.Ny.SeqnoRequestOp:type_name -> proto.Ny.SeqnoRequest
	5, // 3: proto.Ny.ProbeOp:type_name -> proto.Ny.Probe
	3, // 4: proto.Ny.AckRetractOp:type_name -> proto.Ny.AckRetract
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protocol_nylon_proto_init() }
func file_protocol_nylon_proto_init() {
	if File_protocol_nylon_proto != nil {
		return
	}
	file_protocol_nylon_proto_msgTypes[1].OneofWrappers = []any{
		(*Ny_RouteOp)(nil),
		(*Ny_SeqnoRequestOp)(nil),
		(*Ny_ProbeOp)(nil),
		(*Ny_AckRetractOp)(nil),
	}
	file_protocol_nylon_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_nylon_proto_rawDesc), len(file_protocol_nylon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_nylon_proto_goTypes,
		DependencyIndexes: file_protocol_nylon_proto_depIdxs,
		MessageInfos:      file_protocol_nylon_proto_msgTypes,
	}.Build()
	File_protocol_nylon_proto = out.File
	file_protocol_nylon_proto_goTypes = nil
	file_protocol_nylon_proto_depIdxs = nil
}
