// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux && !android

package faketcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTransformer returns the embedded CollectionSpec for transformer.
func loadTransformer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TransformerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load transformer: %w", err)
	}

	return spec, err
}

// loadTransformerObjects loads transformer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*transformerObjects
//	*transformerPrograms
//	*transformerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTransformerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTransformer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// transformerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type transformerSpecs struct {
	transformerProgramSpecs
	transformerMapSpecs
	transformerVariableSpecs
}

// transformerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type transformerProgramSpecs struct {
	FakeTcpEgress  *ebpf.ProgramSpec `ebpf:"fake_tcp_egress"`
	FakeTcpIngress *ebpf.ProgramSpec `ebpf:"fake_tcp_ingress"`
}

// transformerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type transformerMapSpecs struct {
}

// transformerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type transformerVariableSpecs struct {
	ManagedPort *ebpf.VariableSpec `ebpf:"managed_port"`
}

// transformerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTransformerObjects or ebpf.CollectionSpec.LoadAndAssign.
type transformerObjects struct {
	transformerPrograms
	transformerMaps
	transformerVariables
}

func (o *transformerObjects) Close() error {
	return _TransformerClose(
		&o.transformerPrograms,
		&o.transformerMaps,
	)
}

// transformerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTransformerObjects or ebpf.CollectionSpec.LoadAndAssign.
type transformerMaps struct {
}

func (m *transformerMaps) Close() error {
	return _TransformerClose()
}

// transformerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTransformerObjects or ebpf.CollectionSpec.LoadAndAssign.
type transformerVariables struct {
	ManagedPort *ebpf.Variable `ebpf:"managed_port"`
}

// transformerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTransformerObjects or ebpf.CollectionSpec.LoadAndAssign.
type transformerPrograms struct {
	FakeTcpEgress  *ebpf.Program `ebpf:"fake_tcp_egress"`
	FakeTcpIngress *ebpf.Program `ebpf:"fake_tcp_ingress"`
}

func (p *transformerPrograms) Close() error {
	return _TransformerClose(
		p.FakeTcpEgress,
		p.FakeTcpIngress,
	)
}

func _TransformerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed transformer_bpfel.o
var _TransformerBytes []byte
